### ISSUE TITLE
[Container Insights] MissingRegionError

### ISSUE THREAD

**Issue by philross** [Young-ook/terraform-aws-eks#42]
Dear @Young-ook ,

first I wanted to say thank you so much for providing this repo!

I deployed the Amazon CloudWatch Container Insights terraform module (1.4.6) and the metrics part seem fine, but the logs are not working properly.
I found this line in the logs of the logagent: 
```
[error]: #0 unexpected error error_class=Aws::Errors::MissingRegionError error="missing region; use :region option or export region name to ENV['AWS_REGION']"
```

Therefore I edited the deamonset of  eks-cw-containerinsights-logs and added the following line:
```
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              key: logs.region
              name: cluster-info
```
After adding this the logs are recorded properly and are sent to CloudWatch.
